/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentUserView"];
                        "application/json": components["schemas"]["CurrentUserView"];
                        "text/json": components["schemas"]["CurrentUserView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingRecordView"][];
                        "application/json": components["schemas"]["BookingRecordView"][];
                        "text/json": components["schemas"]["BookingRecordView"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBookingRequest"];
                    "text/json": components["schemas"]["CreateBookingRequest"];
                    "application/*+json": components["schemas"]["CreateBookingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingRecordView"];
                        "application/json": components["schemas"]["BookingRecordView"];
                        "text/json": components["schemas"]["BookingRecordView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBookingRequest"];
                    "text/json": components["schemas"]["UpdateBookingRequest"];
                    "application/*+json": components["schemas"]["UpdateBookingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/bookings/by-student/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    studentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingRecordView"][];
                        "application/json": components["schemas"]["BookingRecordView"][];
                        "text/json": components["schemas"]["BookingRecordView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/by-slot/{slotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    fetchGroups?: boolean;
                };
                header?: never;
                path: {
                    slotId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingRecordView"][];
                        "application/json": components["schemas"]["BookingRecordView"][];
                        "text/json": components["schemas"]["BookingRecordView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GroupView"][];
                        "application/json": components["schemas"]["GroupView"][];
                        "text/json": components["schemas"]["GroupView"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateGroupRequest"];
                    "text/json": components["schemas"]["CreateGroupRequest"];
                    "application/*+json": components["schemas"]["CreateGroupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GroupView"];
                        "application/json": components["schemas"]["GroupView"];
                        "text/json": components["schemas"]["GroupView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateGroupRequest"];
                    "text/json": components["schemas"]["UpdateGroupRequest"];
                    "application/*+json": components["schemas"]["UpdateGroupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StudentView"][];
                        "application/json": components["schemas"]["StudentView"][];
                        "text/json": components["schemas"]["StudentView"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateStudentRequest"];
                    "text/json": components["schemas"]["CreateStudentRequest"];
                    "application/*+json": components["schemas"]["CreateStudentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StudentView"];
                        "application/json": components["schemas"]["StudentView"];
                        "text/json": components["schemas"]["StudentView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateStudentRequest"];
                    "text/json": components["schemas"]["UpdateStudentRequest"];
                    "application/*+json": components["schemas"]["UpdateStudentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubjectView"][];
                        "application/json": components["schemas"]["SubjectView"][];
                        "text/json": components["schemas"]["SubjectView"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSubjectRequest"];
                    "text/json": components["schemas"]["CreateSubjectRequest"];
                    "application/*+json": components["schemas"]["CreateSubjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubjectView"];
                        "application/json": components["schemas"]["SubjectView"];
                        "text/json": components["schemas"]["SubjectView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSubjectRequest"];
                    "text/json": components["schemas"]["UpdateSubjectRequest"];
                    "application/*+json": components["schemas"]["UpdateSubjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/subjects/by-teacher/{teacherId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teacherId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubjectView"][];
                        "application/json": components["schemas"]["SubjectView"][];
                        "text/json": components["schemas"]["SubjectView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submission-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubmissionSlotView"][];
                        "application/json": components["schemas"]["SubmissionSlotView"][];
                        "text/json": components["schemas"]["SubmissionSlotView"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSubmissionSlotRequest"];
                    "text/json": components["schemas"]["CreateSubmissionSlotRequest"];
                    "application/*+json": components["schemas"]["CreateSubmissionSlotRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submission-slots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubmissionSlotView"];
                        "application/json": components["schemas"]["SubmissionSlotView"];
                        "text/json": components["schemas"]["SubmissionSlotView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSubmissionSlotRequest"];
                    "text/json": components["schemas"]["UpdateSubmissionSlotRequest"];
                    "application/*+json": components["schemas"]["UpdateSubmissionSlotRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/submission-slots/by-subject/{subjectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    subjectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubmissionSlotView"][];
                        "application/json": components["schemas"]["SubmissionSlotView"][];
                        "text/json": components["schemas"]["SubmissionSlotView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submission-slots/by-teacher/{teacherId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teacherId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubmissionSlotView"][];
                        "application/json": components["schemas"]["SubmissionSlotView"][];
                        "text/json": components["schemas"]["SubmissionSlotView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submission-slots/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    FromDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubmissionSlotView"][];
                        "application/json": components["schemas"]["SubmissionSlotView"][];
                        "text/json": components["schemas"]["SubmissionSlotView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submission-slots/{id}/admissions/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    studentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    studentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submission-slots/{id}/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSubmissionSlotNotificationSettingsRequest"];
                    "text/json": components["schemas"]["UpdateSubmissionSlotNotificationSettingsRequest"];
                    "application/*+json": components["schemas"]["UpdateSubmissionSlotNotificationSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TeacherView"][];
                        "application/json": components["schemas"]["TeacherView"][];
                        "text/json": components["schemas"]["TeacherView"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTeacherRequest"];
                    "text/json": components["schemas"]["CreateTeacherRequest"];
                    "application/*+json": components["schemas"]["CreateTeacherRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teachers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TeacherView"];
                        "application/json": components["schemas"]["TeacherView"];
                        "text/json": components["schemas"]["TeacherView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTeacherRequest"];
                    "text/json": components["schemas"]["UpdateTeacherRequest"];
                    "application/*+json": components["schemas"]["UpdateTeacherRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BookingNotificationMode: number;
        BookingRecordView: {
            /** Format: uuid */
            id: string;
            student: null | components["schemas"]["StudentView"];
            slot: null | components["schemas"]["SubmissionSlotView"];
            /** Format: date-time */
            createdAt: string;
        };
        CreateBookingRequest: {
            /** Format: uuid */
            studentId: string;
            /** Format: uuid */
            slotId: string;
        };
        CreateGroupRequest: {
            name: string;
        };
        CreateStudentRequest: {
            userName: string;
            password: string;
            email: string;
            /** Format: uuid */
            groupId: string;
            firstName: string;
            middleName?: null | string;
            lastName: string;
            /** Format: date */
            birthDate: string;
        };
        CreateSubjectRequest: {
            name: string;
            /** Format: uuid */
            teacherId: string;
            groupIds: string[];
        };
        CreateSubmissionSlotRequest: {
            /** Format: uuid */
            subjectId: string;
            /** Format: uuid */
            teacherId: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            /** Format: int32 */
            maxStudents: number | string;
            allowAllGroups: boolean;
            allowedGroupIds?: null | string[];
            location?: null | string;
            comment?: null | string;
        };
        CreateTeacherRequest: {
            userName: string;
            password: string;
            email: string;
            firstName: string;
            middleName?: null | string;
            lastName: string;
            /** Format: date */
            birthDate: string;
        };
        CurrentUserView: {
            /** Format: uuid */
            id: string;
            userName: null | string;
            email: null | string;
            roles: string[];
        };
        GroupView: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        StudentView: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            middleName?: null | string;
            /** Format: date */
            birthDate: string;
            /** Format: date-time */
            createdAt: string;
            group?: null | components["schemas"]["GroupView"];
        };
        SubjectView: {
            /** Format: uuid */
            id: string;
            name: string;
            teacher: null | components["schemas"]["TeacherView"];
            groups: null | components["schemas"]["GroupView"][];
        };
        SubmissionRemindTime: number;
        SubmissionSlotView: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            /** Format: int32 */
            maxStudents: number | string;
            /** Format: int32 */
            bookingCount: number | string | null;
            allowAllGroups: boolean;
            location?: null | string;
            comment?: null | string;
            subject?: null | components["schemas"]["SubjectView"];
            teacher?: null | components["schemas"]["TeacherView"];
            allowedGroups?: null | components["schemas"]["GroupView"][];
            admittedStudents?: null | components["schemas"]["StudentView"][];
            notificationSettings?: null | components["schemas"]["SubmissionSlotNotificationSettingsView"][];
        };
        SubmissionSlotNotificationSettingsView: {
            /** Format: uuid */
            userId: string;
            submissionRemindTimes: components["schemas"]["SubmissionRemindTime"][];
            bookingNotificationMode?: null | components["schemas"]["BookingNotificationMode"];
        };
        TeacherView: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            middleName?: null | string;
            /** Format: date */
            birthDate: string;
            /** Format: date-time */
            createdAt?: null | string;
        };
        UpdateBookingRequest: {
            /** Format: uuid */
            studentId?: null | string;
            /** Format: uuid */
            slotId?: null | string;
        };
        UpdateGroupRequest: {
            name?: null | string;
        };
        UpdateStudentRequest: {
            /** Format: uuid */
            groupId?: null | string;
            firstName?: null | string;
            lastName?: null | string;
            middleName?: null | string;
            /** Format: date */
            birthDate?: null | string;
        };
        UpdateSubjectRequest: {
            name?: null | string;
            /** Format: uuid */
            teacherId?: null | string;
            groupIds?: null | string[];
        };
        UpdateSubmissionSlotNotificationSettingsRequest: {
            /** Format: uuid */
            userId: string;
            submissionRemindTimes: components["schemas"]["SubmissionRemindTime"][];
            bookingNotificationMode?: null | components["schemas"]["BookingNotificationMode"];
        };
        UpdateSubmissionSlotRequest: {
            /** Format: uuid */
            subjectId?: null | string;
            /** Format: uuid */
            teacherId?: null | string;
            /** Format: date-time */
            startTime?: null | string;
            /** Format: date-time */
            endTime?: null | string;
            /** Format: int32 */
            maxStudents?: null | number | string;
            allowAllGroups?: null | boolean;
            allowedGroupIds?: null | string[];
            location?: null | string;
            comment?: null | string;
        };
        UpdateTeacherRequest: {
            firstName?: null | string;
            lastName?: null | string;
            middleName?: null | string;
            /** Format: date */
            birthDate?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
