services:
  postgres:
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data

  kafka:
    volumes:
      - type: tmpfs
        target: /tmp/kafka-logs

  booking-api:
    ports:
      - "${BOOKING_API_PORT:-8081}:8081"

  data-import-api:
    ports:
      - "${DATA_IMPORT_API_PORT:-8083}:8083"
